export default [
  { city: "Boaco", country: "Nicaragua", country: "Nicaragua" },
  { city: "Carazo", country: "Nicaragua", country: "Nicaragua" },
  { city: "Chinandega", country: "Nicaragua" },
  { city: "Chontales", country: "Nicaragua" },
  { city: "Costa Caribe Norte", country: "Nicaragua" },
  { city: "Costa Caribe Sur", country: "Nicaragua" },
  { city: "Estelí", country: "Nicaragua" },
  { city: "Granada", country: "Nicaragua" },
  { city: "Jinotega", country: "Nicaragua" },
  { city: "León", country: "Nicaragua" },
  { city: "Madriz", country: "Nicaragua" },
  { city: "Managua", country: "Nicaragua" },
  { city: "Masaya", country: "Nicaragua" },
  { city: "Matagalpa", country: "Nicaragua" },
  { city: "Nueva Segovia", country: "Nicaragua" },
  { city: "Río San Juan", country: "Nicaragua" },
  { city: "Rivas", country: "Nicaragua" },
];
